use mydb;

/* INSERTAR HORARIOS*/
CALL insertTimes('Lunes', '7:00 - 8:00', @response);
select @response;
CALL insertTimes('Lunes', '8:00 - 9:00', @response);
select @response;
CALL insertTimes('Lunes', '9:00 - 10:00', @response);
select @response;
CALL insertTimes('Lunes', '10:00 - 11:00', @response);
select @response;
CALL insertTimes('Lunes', '11:00 - 12:00', @response);
select @response;
CALL insertTimes('Lunes', '12:00 - 13:00', @response);
select @response;
CALL insertTimes('Lunes', '13:00 - 14:00', @response);
select @response;
CALL insertTimes('Martes', '7:00 - 8:00', @response);
select @response;
CALL insertTimes('Martes', '8:00 - 9:00', @response);
select @response;
CALL insertTimes('Martes', '9:00 - 10:00', @response);
select @response;
CALL insertTimes('Martes', '10:00 - 11:00', @response);
select @response;
CALL insertTimes('Martes', '11:00 - 12:00', @response);
select @response;
CALL insertTimes('Martes', '12:00 - 13:00', @response);
select @response;
CALL insertTimes('Martes', '13:00 - 14:00', @response);
select @response;
CALL insertTimes('Miercoles', '7:00 - 8:00', @response);
select @response;
CALL insertTimes('Miercoles', '8:00 - 9:00', @response);
select @response;
CALL insertTimes('Miercoles', '9:00 - 10:00', @response);
select @response;
CALL insertTimes('Miercoles', '10:00 - 11:00', @response);
select @response;
CALL insertTimes('Miercoles', '11:00 - 12:00', @response);
select @response;
CALL insertTimes('Miercoles', '12:00 - 13:00', @response);
select @response;
CALL insertTimes('Miercoles', '13:00 - 14:00', @response);
select @response;
CALL insertTimes('Jueves', '7:00 - 8:00', @response);
select @response;
CALL insertTimes('Jueves', '8:00 - 9:00', @response);
select @response;
CALL insertTimes('Jueves', '9:00 - 10:00', @response);
select @response;
CALL insertTimes('Jueves', '10:00 - 11:00', @response);
select @response;
CALL insertTimes('Jueves', '11:00 - 12:00', @response);
select @response;
CALL insertTimes('Jueves', '12:00 - 13:00', @response);
select @response;
CALL insertTimes('Jueves', '13:00 - 14:00', @response);
select @response;
CALL insertTimes('Viernes', '7:00 - 8:00', @response);
select @response;
CALL insertTimes('Viernes', '8:00 - 9:00', @response);
select @response;
CALL insertTimes('Viernes', '9:00 - 10:00', @response);
select @response;
CALL insertTimes('Viernes', '10:00 - 11:00', @response);
select @response;
CALL insertTimes('Viernes', '11:00 - 12:00', @response);
select @response;
CALL insertTimes('Viernes', '12:00 - 13:00', @response);
select @response;
CALL insertTimes('Viernes', '13:00 - 14:00', @response);
select @response;

/* INSERTAR PROFESORES*/
CALL insertTeacher('Ernesto Alonso','Solis','Galindo', @response);
select @response;
CALL insertTeacher('Luis Rodolfo','Coello','Galindo', @response);
select @response;
CALL insertTeacher('Jorge','Bautista','Lopez', @response);
select @response;
CALL insertTeacher('Jorge Manuel','Ortega','Martinez', @response);
select @response;
CALL insertTeacher('Israel','Acuña','Galvan', @response);
select @response;
CALL insertTeacher('Ingrid Berenice','Reyes','Escudero', @response);
select @response;
CALL insertTeacher('Nestor Andes','Montiel','Hernandez', @response);
select @response;
CALL insertTeacher('Juana Neiry','Luna','Morales', @response);
select @response;
CALL insertTeacher('Irene','Campos','Gonzales', @response);
select @response;
CALL insertTeacher('Ernesto','Flores','Garcia', @response);
select @response;

/* INSERTAR AULAS*/

CALL insertRoom("A2M1", 50, @response);
CALL insertRoom("A2M1", 30, @response);
CALL insertRoom("A3M1", 40, @response);
CALL insertRoom("A4M1", 30, @response);
CALL insertRoom("A5M1", 50, @response);
CALL insertRoom("A6M1", 40, @response);
CALL insertRoom("A7M1", 30, @response);
CALL insertRoom("A8M1", 40, @response);
CALL insertRoom("A9M1", 50, @response);
CALL insertRoom("A10M1", 30, @response);
CALL insertRoom("A1M2", 50, @response);
CALL insertRoom("A2M2", 30, @response);
CALL insertRoom("A3M2", 40, @response);
CALL insertRoom("A4M2", 30, @response);
CALL insertRoom("A5M2", 50, @response);
CALL insertRoom("A6M2", 40, @response);
CALL insertRoom("A7M2", 30, @response);
CALL insertRoom("A8M2", 40, @response);
CALL insertRoom("A9M2", 50, @response);
CALL insertRoom("A10M2", 30, @response);
CALL insertRoom("A1M3", 50, @response);
CALL insertRoom("A2M3", 30, @response);
CALL insertRoom("A3M3", 40, @response);
CALL insertRoom("A4M3", 30, @response);
CALL insertRoom("A5M3", 50, @response);
CALL insertRoom("A6M3", 40, @response);
CALL insertRoom("A7M3", 30, @response);
CALL insertRoom("A8M3", 40, @response);
CALL insertRoom("A9M3", 50, @response);
CALL insertRoom("A10M3", 30, @response);

/* INSERTAR MODULOS*/

CALL insertModule("FP1", "Fundamentos de Programacion", 1, @response);
CALL insertModule("IME1", "Interaccion Materia y Energia", 3, @response);
CALL insertModule("EA1", "Electronica Analogica", 2, @response);
CALL insertModule("EcD1", "Ecuaciones Diferenciales", 4, @response);
CALL insertModule("AC1", "Arquitectira de Computadoras", 6, @response);
CALL insertModule("MN1", "Metodos Numericos", 7, @response);
CALL insertModule("EsD1", "Estructura de Datos", 5, @response);
CALL insertModule("CE1", "Causa y Efecto. Lengua Extranjera", 8, @response);
CALL insertModule("EP1", "En otras palabras...Lengua Extranjera", 9, @response);
CALL insertModule("CDI1", "Calculo Diferencial e Integral", 4, @response);
CALL insertModule("CDI1", "Calculo Diferencial e Integral", 5, @response);
CALL insertModule("CI1", "Capacitacion en la Industria", 1, @response);
CALL insertModule("NLR1", "Normas, Leyes y Reglamentos de Ingenieria en Computacion", 3, @response);
CALL insertModule("NLR1", "Normas, Leyes y Reglamentos de Ingenieria en Computacion", 7, @response);
CALL insertModule("O41", "Optativa 4(Implementacion de Protocolos de Comunicacion en Hardware)", 2, @response);
CALL insertModule("O41", "Optativa 4(Implementacion de Protocolos de Comunicacion en Hardware)", 6, @response);
CALL insertModule("RP1", "Redes y Protocolos Industriales", 2, @response);
CALL insertModule("RP1", "Redes y Protocolos Industriales", 10, @response);
CALL insertModule("AL1", "Algebra Lineal", 10, @response);

/* INSERTAR GRUPOS*/

CALL insertGroups(10, 1, @response);
CALL insertGroups(10, 1, @response);
CALL insertGroups(10, 1, @response);
CALL insertGroups(10, 1, @response);
CALL insertGroups(10, 1, @response);
CALL insertGroups(10, 2, @response);
CALL insertGroups(10, 3, @response);
CALL insertGroups(10, 4, @response);
CALL insertGroups(20, 5, @response);
CALL insertGroups(20, 6, @response);
CALL insertGroups(20, 7, @response);
CALL insertGroups(20, 8, @response);
CALL insertGroups(27, 5, @response);
CALL insertGroups(27, 2, @response);
CALL insertGroups(27, 8, @response);
CALL insertGroups(27, 9, @response);
CALL insertGroups(32, 1, @response);
CALL insertGroups(32, 12, @response);
CALL insertGroups(32, 9, @response);
CALL insertGroups(32, 15, @response);
CALL insertGroups(18, 12, @response);
CALL insertGroups(18, 14, @response);
CALL insertGroups(18, 13, @response);
CALL insertGroups(18, 9, @response);
CALL insertGroups(28, 1, @response);
CALL insertGroups(18, 1, @response);
CALL insertGroups(30, 1, @response);
CALL insertGroups(10, 1, @response);
CALL insertGroups(14, 1, @response);
CALL insertGroups(18, 1, @response);
CALL insertGroups(22, 1, @response);
CALL insertGroups(26, 1, @response);
CALL insertGroups(19, 1, @response);
CALL insertGroups(29, 1, @response);
CALL insertGroups(31, 1, @response);
CALL insertGroups(35, 1, @response);
CALL insertGroups(25, 1, @response);
CALL insertGroups(19, 1, @response);
CALL insertGroups(21, 1, @response);